"""Add Smart Contract Model 5

Revision ID: 17746a877c10
Revises: 180bd7029628
Create Date: 2024-07-31 05:58:02.512371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17746a877c10'
down_revision = '180bd7029628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_contract_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentation', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('compiler_version', sa.String(length=255), nullable=False))
        batch_op.drop_column('code_functions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_contract_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_functions', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('compiler_version')
        batch_op.drop_column('documentation')

    # ### end Alembic commands ###
