"""Add Smart Contract Model 4

Revision ID: 180bd7029628
Revises: 7b51cd8e6b6d
Create Date: 2024-07-29 04:47:43.500798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180bd7029628'
down_revision = '7b51cd8e6b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_contract_version', schema=None) as batch_op:
        batch_op.drop_column('version_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_contract_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
