"""Add Smart Contract Model 2

Revision ID: 39f854edf03b
Revises: 81d905dbdcce
Create Date: 2024-07-28 23:01:30.232155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f854edf03b'
down_revision = '81d905dbdcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=True),
    sa.Column('deployed_id', sa.String(length=255), nullable=True),
    sa.Column('network', sa.String(length=255), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('contract_type', sa.String(length=255), nullable=False),
    sa.Column('code_requirements', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart_contract')
    # ### end Alembic commands ###
