"""Add Smart Contract Model 6

Revision ID: 4d91a99a0762
Revises: 17746a877c10
Create Date: 2024-08-02 03:01:23.394651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d91a99a0762'
down_revision = '17746a877c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coinbase_wallet_address', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('coinbase_wallet_address')

    # ### end Alembic commands ###
