"""Fix Models

Revision ID: 7b51cd8e6b6d
Revises: 39f854edf03b
Create Date: 2024-07-29 00:52:27.209296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b51cd8e6b6d'
down_revision = '39f854edf03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('smart_contract_deployed_version_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('contract_type')
        batch_op.drop_column('deployed_version_id')
        batch_op.drop_column('code_requirements')

    with op.batch_alter_table('smart_contract_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('contract_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('code_requirements', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('deployed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_contract_version', schema=None) as batch_op:
        batch_op.drop_column('deployed')
        batch_op.drop_column('code_requirements')
        batch_op.drop_column('contract_type')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('smart_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_requirements', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('deployed_version_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contract_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('smart_contract_deployed_version_id_fkey', 'smart_contract_version', ['deployed_version_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
