"""Add Smart Contract Model

Revision ID: 81d905dbdcce
Revises: 70e7175f505c
Create Date: 2024-07-28 22:58:35.425822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d905dbdcce'
down_revision = '70e7175f505c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_contract_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_functions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_api_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('metamask_wallet_address', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('metamask_wallet_address')
        batch_op.drop_column('openai_api_key')

    op.drop_table('smart_contract_version')
    # ### end Alembic commands ###
